- alias: 'Keep Aurică cool'
  trigger:
    platform: time_pattern
    minutes: '*'
    seconds: '0'
  action:
    entity_id: switch.ac
    service_template: >
      {% if states.sensor.living_temperature.state | float > 27 and states.switch.ac.state == 'off' %}
      switch.turn_on
      {% elif states.sensor.living_temperature.state| float < 25 and states.switch.ac.state == 'on' %}
      switch.turn_off
      {% else %}
      script.do_nothing
      {% endif %}

- alias: 'Remote'
  trigger:
    platform: state
    entity_id: sensor.0x000d6ffffe0b266b_action
    to: 'toggle'
  action:
    entity_id: switch.ac
    service: switch.toggle
